spring:
  application:
    name: moneywise
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/moneywise}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
